/*
 * Biwse API V1 Reference
 *
 * This API documentation generated from OpenAPI specification. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package biwse

type Payment struct {
	// Recipient address
	Address string `json:"address"`
	// Amount to send.
	Amount float32 `json:"amount"`
}
