/*
 * Biwse API V1 Reference
 *
 * This API documentation generated from OpenAPI specification. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package biwse

type AppInvoiceCreated struct {
	// Invoice ID
	Id string `json:"id,omitempty"`
	// Invoice page URL
	Url string `json:"url,omitempty"`
}
