/*
 * Biwse API V1 Reference
 *
 * This API documentation generated from OpenAPI specification. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package biwse

type WalletInvoice struct {
	// Invoice's amount
	Amount float32 `json:"amount"`
	// Callback url
	CallbackLink string `json:"callback_link,omitempty"`
	// Redirect user after payment
	SuccessUrl string `json:"success_url,omitempty"`
}
