/*
 * Biwse API V1 Reference
 *
 * This API documentation generated from OpenAPI specification. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package biwse

type Transaction struct {
	// Sended transaction ID
	TxHash string `json:"tx_hash,omitempty"`
}
