/*
 * Biwse API V1 Reference
 *
 * This API documentation generated from OpenAPI specification. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package biwse

type InvoiceStatus struct {
	// Invoice's amount
	Msg string `json:"msg,omitempty"`
	Data InvoiceStatusData `json:"data,omitempty"`
}
