/*
 * Biwse API V1 Reference
 *
 * This API documentation generated from OpenAPI specification. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package biwse

type AppInvoice struct {
	// Invoice's amount
	AmountUsd float32 `json:"amount_usd"`
	// Callback url
	CallbackLink string `json:"callback_link,omitempty"`
	// Redirect user after payment
	SuccessUrl string `json:"success_url,omitempty"`
	// Your invoice internal identifier
	InvoiceNumber string `json:"invoice_number,omitempty"`
}
